version: '3.8'

services:
  db:
    image: mysql:8
    container_name: futvia-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: futvia
      MYSQL_USER: root
      MYSQL_PASSWORD: futvia_pass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
